[params]
    title = "Jean-Dominique Trouillard"
    description = "Mon Portfolio & Articles"
    
    # Infos de base
    [params.about]
        enable = true
        title = "À propos de moi"
        content = "Je suis passionné par le développement web et le cloud. Bienvenue sur mon site exposé via Cloudflare !"
        image = "https://raw.githubusercontent.com/gurusabarish/hugo-profile/main/images/avatar.png" # Image de test

    # Activation des sections
    [params.sections]
        about = true
        experience = true
        blog = true
